// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://avehqlehgzayvxoaikbs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF2ZWhxbGVoZ3pheXZ4b2Fpa2JzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3NTAwMjIsImV4cCI6MjA3MzMyNjAyMn0.K4VhsJ0L5G_EhyFUPk90_2A5oNEofB0xAQHUsgpWuaA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});